{% import_yaml '/srv/salt/vars.yml' as vars %}

base: &base
  adapter: sqlite3
  timeout: 5000

development:
  database: db/development.sqlite3
  <<: *base

test:
  database: db/test.sqlite3
  <<: *base

private:
  adapter: postgresql
  host: localhost
  database: pwpusher
  username: pwpusher_database_user
  password: {{ vars['database_password'] }}
  pool: 5
  timeout: 5000
  encoding: utf8
  reconnect: false

production:
  adapter: postgresql
  host: localhost
  database: pwpusher
  username: pwpusher_database_user
  password: {{ vars['database_password'] }}
  pool: 5
  timeout: 5000
  encoding: utf8
  reconnect: false

